[tool.poetry]
name = "theory-gpt"
version = "0.1.0"
description = ""
authors = ["samsepi0l-4172 <89460136+samsepi0l-4172@users.noreply.github.com>"]
license = "GNU"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
black = "^24.8.0"
crewai = {extras = ["tools"], version = "*"}
ipykernel = "^6.29.5"
langchain = "*"
langchain-groq = "*"
langchain-openai = "*"
langgraph = "*"
pydub = "^0.25.1"
streamlit = "^1.39.0"
yfinance = "^0.2.44"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79